#!/bin/bash
echo "═══════════════════════════════════════"
echo "  Ralph Decisions & Blocked Review"
echo "═══════════════════════════════════════"
echo ""
echo "📋 DECISIONS MADE (review these):"
echo "---"
grep "DECISION:" progress.txt 2>/dev/null || echo "None logged"
echo ""
echo "🚫 BLOCKED (need your input):"
echo "---"
grep "BLOCKED:" progress.txt 2>/dev/null || echo "None blocked"
echo ""
echo "📊 TASK PROGRESS:"
echo "---"
echo "Done: $(grep -c '\- \[x\]' prd.md) / Total: $(grep -c '\- \[.\]' prd.md)"
echo ""
echo "═══════════════════════════════════════"
